stages:
  - build
  - deploy


build_job:
  stage: build  # the build process will only be started by git tag commits
  tags:
    - build
  image: php:7.4-cli
  before_script:
    - apt-get update && apt-get install -y git unzip
    - cp .env.example .env
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
    - php -r "unlink('composer-setup.php');"
    
  script:
      
      - composer validate --no-check-publish && composer install --prefer-dist --no-progress

  artifacts:
    expire_in: 1 week  # save gitlab server space, we copy the files we need to deploy folder later on
    paths:
      - ./bin/

deploy_job:
  stage: deploy
  tags:
    - deploy
  image: mcr.microsoft.com/azure-cli
  dependencies:
    - build_job
  before_script:
    - 'cd bin'
    - 'zip -r ./artifacts.zip .'
    - 'az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID'
    - 'az account set --subscription $AZURE_SUBSCRIPTION_ID'
    
  
  script:
    - az webapp deployment source config-zip --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_WEBAPP_NAME --src ./artifacts.zip
